apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.configSecretName | lower | quote }}
  labels:
    app.kubernetes.io/name: mongo
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.config.rootUser | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.config.rootPassword | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.config.octofarmDbName | quote }}

