apiVersion: v1
kind: Service
metadata:
  name: octofarm
  labels:
    app.kubernetes.io/name: octofarm
spec:
  ports:
    - port: {{ .Values.octofarm.service.port }}
      name: {{ .Values.octofarm.service.portName }}
      targetPort: {{ .Values.octofarm.service.portName }}
  clusterIP: None
  selector:
    app.kubernetes.io/name: octofarm

