apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.octofarm.configSecretName | quote }}
  labels:
    app.kubernetes.io/name: octofarm
stringData:
  {{- $user := .Values.mongodb.config.rootUser }}
  {{- $pass := .Values.mongodb.config.rootPassword }}
  {{- $db := .Values.mongodb.config.octofarmDbName }}
  MONGO: mongodb://{{ $user }}:{{ $pass }}@localhost:27017/{{ $db }}?authSource=admin
  OCTOFARM_PORT: {{ .Values.octofarm.config.listenPort | quote }}
  TZ: {{ .Values.octofarm.timeZone | quote }}

